import * as igs from './gs.js';
import * as igns from './gns.js';
import * as igls from './gls.js';
import * as iabout from './about.js';
import * as iseturl from './seturl.js';
import * as itoggleinterval from './toggleinterval.js';
import * as iintervals from './intervals.js';
import * as ihelp from './help.js';
import * as iwand from './wand.js';
import * as igas from './gas.js';
import * as istart_server from './start_server.js';
import * as igetdata from './getdata.js';
import * as igetconfig from './getconfig.js';
import * as isetdata from './setdata.js';
import * as iedit from './edit.js';
export const gs = igs;
export const gns = igns;
export const gls = igls;
export const about = iabout;
export const seturl = iseturl;
export const toggleinterval = itoggleinterval;
export const intervals = iintervals;
export const help = ihelp;
export const wand = iwand;
export const gas = igas;
export const start_server = istart_server;
export const getdata = igetdata;
export const getconfig = igetconfig;
export const setdata = isetdata;
export const edit = iedit;
export default [gs, gns, gls, about, seturl, toggleinterval, intervals, help, wand, gas, start_server, getdata, getconfig, setdata, edit];